language: ruby
rvm:
  - 1.8.7
notifications:
  email:
    - x-way@waterwave.ch
env:
  - PUPPET_VERSION=2.6.2
  - PUPPET_VERSION=2.7.18
  - PUPPET_VERSION=3.1.1
script:
  - "rake lint"
  - "rake --trace spec"
