rvm: 1.8.7
notifications:
  email:
    - x-way@waterwave.ch
env:
  - PUPPET_VERSION=2.6.2
  - PUPPET_VERSION=2.7.14
  - PUPPET_VERSION=3.1.1
before_script:
  - 'git clone git://github.com/x-way/puppet-concat.git spec/fixtures/modules/concat'
