class interfaces {
  include concat::setup

  concat{'/etc/network/interfaces':
    owner => root,
    group => root,
    mode => 644,
  }

  concat::fragment{'interfaces_header':
    target => '/etc/network/interfaces',
    content => "# This file describes the network interfaces available on your system\n# and how to activate them. For more information, see interfaces(5).\n\n# Generated by puppet for ${fqdn}, DO NOT MODIFY!\n\n",
    order => 01,
  }
}
